### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-erb#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://lit-garden-3730.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-erb/1) criteria:
- [x] The root of your site (`/`) has a form to collect information that will be embedded in the dating profile
- [x] Submitting the form at the root of the site creates a new dating profile at `/profile`
- [x] One of the form inputs takes the URL of an image to be displayed on the generated profile
- [x] Any CSS or JavaScript is embedded in the page with a `style` or `script` element (we'll learn about including other files in a later lesson)
- [x](optional) For an added challenge, use [the free Formspree service](http://formspree.io/) to generate a contact form on the profile page, so that interested parties have a way of getting in touch with the creator of the profile

... I got a little carried away. 

**How would I set fallback values for my form inputs, in case someone didn't answer all the questions? Can I put conditionals in erb files?**

**Comment by chrisvfritz** [comment]
Woah! Thanks for teaching me about the color input type. I've never seen that before! :smiley: And I love that you even show the color on the page. I do see a couple things that could be fixed though:
- Images can sometimes overflow their width currently
- The form looks like it's always sending to your own email address, rather than the email address of the person who set up the profile

See if you can fix those two things, then it should be ready for approval!

**Comment by KatieMFritz** [comment]
Done.

**Comment by chrisvfritz** [comment]
Looks good! :smiley: This is worthy of a :shipit:, but one more bonus tip is you can prevent people from submitting blank fields by adding the `required` attribute to form inputs. It's kind of a weird attribute in that you don't need `required="anything"` - just the word `required`.
